### ISSUE TITLE
Working with git bare repository

### ISSUE THREAD

**Issue by little-flag** [doekman/osagitfilter#8]
I'm attempting to use osagitfilter with a git bare repository and having only partial success. The bare repository is a very efficient method for tracking lots of scripts, spread across multiple directories, without having to use symlinks, so it'd be nice if I could get it working.

A bare repository can't have a .gitattributes file, but I was able to get git to recognise the filter by placing `*.scpt filter=osa` in info/attributes (relative to the bare repository). However, here's the problem:

```
do shell script "/usr/bin/git --git-dir=$HOME/gitscr --work-tree=$HOME add " & quoted form of thePath
> /usr/local/bin/osagitfilter: line 128: osagetlang: command not found
error: external filter '/usr/local/bin/osagitfilter clean %f' failed 127
error: external filter '/usr/local/bin/osagitfilter clean %f' failed
fatal: clean filter 'osa' failed
```

The above command works fine if run directly in the terminal but doesn’t work when embedded in AppleScript. This approach only really works if it can be automated, so this is a problem!

Any ideas?

FWIW the script to set up the bare repository is as follows:

```
GITSCR=~/[path goes here]
mkdir $GITSCR
git init --bare $GITSCR
git --git-dir=$GITSCR --work-tree=$HOME config --local status.showUntrackedFiles no
mkdir $GITSCR/info
touch $GITSCR/info/attributes
echo "*.scpt filter=osa" >> $GITSCR/info/attributes
```

Thanks.

**Comment by doekman** [comment]
The script `/usr/local/bin/osagitfilter` expects to find `osagetlang` in the current path. So you could add `/usr/local/bin` to your path, before executing git:

    do shell script "export PATH=/usr/local/bin:$PATH; /usr/bin/git --git-dir=$HOME/gitscr --work-tree=$HOME add " & quoted form of thePath

Does this fix the issue?

**Comment by little-flag** [comment]
It seems that solves one problem and leads to another. Now I get the error:
`fatal: not a git repository: [path]`

**Comment by doekman** [comment]
Hmm, that sounds more like a git-error.

Maybe you could try running the command from the command line. Notice not all shell-variables are set when you run from shell scripts via AppleScript.

I found [this technote](https://developer.apple.com/library/archive/technotes/tn2065/_index.html) invaluable when working with `do shell script`.

**Comment by little-flag** [comment]
No worries, I am probably just overcomplicating things. I will figure out a simpler solution. Thanks for your help!

**Comment by doekman** [comment]
Happy to help. Success with your project.
